Development
redBorder/cookbook-rb-exporter pull request #5
Opened 2024-07-09 12:50 UTC by jsotofernandez

By @davidredborder 
    - [c1ee0f3] fix netflow v5
    - [4a06b54] add subnet to observation id filters

2024-07-09 14:49 UTC, JPeraltaNic approved these changes

2024-07-09 16:36 UTC, ljblancoredborder requested changes

2024-07-09 16:36 UTC, ljblancoredborder commented on packaging/rpm/Makefile
> +		-o packaging/rpm/SOURCES/$(PACKAGE_NAME)-$(VERSION).tar.gz HEAD
instead of HEAD, $(LATEST) to have more control on the param

2024-07-09 16:36 UTC, ljblancoredborder commented on resources/templates/default/rb-exporter_pretag_map.erb
> +  set_tag2=<%= observation_id_filter['observation_id'] %> filter='src net <%= observation_id_filter['subnet'] %>'
tab to the left

2024-07-09 16:36 UTC, ljblancoredborder commented on resources/templates/default/rb-exporter_pretag_map.erb
> +  set_tag2=<%= observation_id_filter['observation_id'] %> filter='dst net <%= observation_id_filter['subnet'] %>'
tab to the left

2024-07-10 08:21 UTC, jsotofernandez commented on packaging/rpm/Makefile
> +		-o packaging/rpm/SOURCES/$(PACKAGE_NAME)-$(VERSION).tar.gz HEAD
Where is HEAD used here?

2024-07-10 08:50 UTC, merged